server:
  port: 8081

spring:
  application:
    name: AldeamoService

resilience4j:
  circuitbreaker:
    instances:
      notificacionService:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
